version: '3'
services:
  nginx:
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    ports:
        - "8080:80"
    volumes:
        - .:/app:cached
        - ./docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
        - php
    links:
        - php
  php:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
        - .:/app:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    depends_on:
        - mysql
    links:
        - mysql
  mysql:
    image: mysql:5.6
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_DATABASE: 'todos_database'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'
        MYSQL_ROOT_PASSWORD: 'root'
