version: '3'
services:
  php:
    container_name: php_test
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
        - .:/var/www/html:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    depends_on:
        - mysql
    links:
        - mysql
  mysql:
    container_name: mysql_test
    image: mysql:5.6
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_DATABASE: 'todos_database'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'
        MYSQL_ROOT_PASSWORD: 'root'
